CREATE TABLE IF NOT EXISTS `PARAMETER_MAPPING` (
    `TABLE_NAME` VARCHAR(128) NOT NULL,
    `PARAMETER_CODE` VARCHAR(128) NOT NULL,
    `COLUMN_NAME` VARCHAR(128) NOT NULL,
    PRIMARY KEY (`TABLE_NAME`, `PARAMETER_CODE`)
);

INSERT INTO `PARAMETER_MAPPING` (`TABLE_NAME`, `PARAMETER_CODE`, `COLUMN_NAME`) VALUES
    ('LOAD_PROFILE', 'P2-1-1-4-0', 'CURRENT_R'),
    ('LOAD_PROFILE', 'P2-1-2-4-0', 'CURRENT_Y'),
    ('LOAD_PROFILE', 'P2-1-3-4-0', 'CURRENT_B'),
    ('LOAD_PROFILE', 'P1-2-1-4-0', 'VOLTAGE_R'),
    ('LOAD_PROFILE', 'P1-2-2-4-0', 'VOLTAGE_Y'),
    ('LOAD_PROFILE', 'P1-2-3-4-0', 'VOLTAGE_B'),
    ('LOAD_PROFILE', 'P7-1-18-1-0', 'KWH'),
    ('LOAD_PROFILE', 'P7-1-18-2-0', 'KVAH'),
    ('LOAD_PROFILE', 'P7-3-18-2-0', 'POWER'),
    ('LOAD_PROFILE', 'P7-2-1-0-0', 'KVARH_LAG'),
    ('LOAD_PROFILE', 'P7-2-2-0-0', 'KVARH_LEAD'),
    ('DAY_PROFILE', 'P7-1-18-2-0', 'KWH_FORWARDED_TOTAL'),
    ('DAY_PROFILE', 'P7-1-18-1-0', 'KWH_FORWARDED_FUND'),
    ('DAY_PROFILE', 'P7-1-5-1-0', 'KWH_IMPORT_FUND'),
    ('DAY_PROFILE', 'P7-1-6-2-0', 'KWH_EXPORT_TOTAL'),
    ('DAY_PROFILE', 'P7-1-6-1-0', 'KWH_EXPORT_FUND'),
    ('DAY_PROFILE', 'P7-3-18-2-0', 'KVAH_FORWARDED_TOTAL'),
    ('DAY_PROFILE', 'P7-3-5-2-0', 'KVAH_IMPORT_TOTAL'),
    ('DAY_PROFILE', 'P7-3-6-0-0', 'KVAH_EXPORT_TOTAL'),
    ('DAY_PROFILE', 'P7-2-1-0-0', 'KVARH_Q1_LAG'),
    ('DAY_PROFILE', 'P7-2-2-0-0', 'KVARH_Q2_LEAD'),
    ('DAY_PROFILE', 'P7-2-3-0-0', 'KVARH_Q3'),
    ('DAY_PROFILE', 'P7-2-4-0-0', 'KVARH_Q4'),
    ('DAY_PROFILE', 'P1202-1-5-2-0', 'KWH_IMPORT_TOTAL_SNAPSHOT'),
    ('DAY_PROFILE', 'P1203-1-14-1-0', 'KWH_FORWARDED_FUND_SNAPSHOT'),
    ('DAY_PROFILE', 'P1202-2-19-0-0', 'KVARH_Q1_SNAPSHOT'),
    ('DAY_PROFILE', 'P1202-2-20-0-0', 'KVARH_Q4_SNAPSHOT')
ON DUPLICATE KEY UPDATE
    `COLUMN_NAME` = VALUES(`COLUMN_NAME`);
